apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-leaking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-leaking-app
      restype: pod
  template:
    metadata:
      labels:
        app: my-leaking-app
        restype: pod
    spec:
      shareProcessNamespace: true
      
      containers:
      
      - image: johnsonxd4/my-leaking-app:1.0.0
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        name: my-leaking-app
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        volumeMounts:
        - mountPath: /tmp
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 500Mi
     